# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "snowflake" {
  account  = var.snowflake_account
  region   = var.snowflake_region
  username = var.snowflake_user

  private_key_path = var.snowflake_key_path
  role             = var.snowflake_security_role
}

variable "snowflake_account" {}
variable "snowflake_region" {}
variable "snowflake_user" {}
variable "snowflake_role" {}
variable "snowflake_security_role" {}
variable "snowflake_key_path" {}
